[
    "event AddValidator(address indexed validator, address votePool)",
    "event ChangeAdmin(address indexed admin)",
    "event UpdateFoundationAddress(address foundation)",
    "event UpdateParams(uint8 posCount, uint8 posBackup, uint8 poaCount, uint8 poaBackup)",
    "event UpdateRates(uint256 burnRate, uint256 foundationRate)",
    "event WithdrawFoundationReward(address receiver, uint256 amount)",
    "function JailPeriod() view returns (uint256)",
    "function MarginLockPeriod() view returns (uint256)",
    "function MaxValidators() view returns (uint16)",
    "function PercentChangeLockPeriod() view returns (uint256)",
    "function PoaMinMargin() view returns (uint256)",
    "function PosMinMargin() view returns (uint256)",
    "function PunishAmount() view returns (uint256)",
    "function WithdrawLockPeriod() view returns (uint256)",
    "function addValidator(address _validator, address _manager, uint256 _percent, uint8 _type) returns (address)",
    "function admin() view returns (address)",
    "function allValidators(uint256) view returns (address)",
    "function backupCount(uint8) view returns (uint8)",
    "function burnRate() view returns (uint256)",
    "function changeAdmin(address _newAdmin)",
    "function count(uint8) view returns (uint8)",
    "function distributeBlockReward() payable",
    "function foundation() view returns (address)",
    "function foundationRate() view returns (uint256)",
    "function foundationReward() view returns (uint256)",
    "function getActiveValidators() view returns (address[])",
    "function getAllValidatorsLength() view returns (uint256)",
    "function getBackupValidators() view returns (address[])",
    "function getTopValidators() view returns (address[])",
    "function improveRanking()",
    "function initialize(address[] _validators, address[] _managers, address _admin)",
    "function initialized() view returns (bool)",
    "function lowerRanking()",
    "function pendingReward(address) view returns (uint256)",
    "function punishContract() view returns (address)",
    "function removeRanking()",
    "function updateActiveValidatorSet(address[] newSet, uint256 epoch)",
    "function updateFoundation(address _foundation)",
    "function updateParams(uint8 _posCount, uint8 _posBackup, uint8 _poaCount, uint8 _poaBackup)",
    "function updateRates(uint256 _burnRate, uint256 _foundationRate)",
    "function updateValidatorState(address _validator, bool pause)",
    "function validatorsContract() view returns (address)",
    "function votePools(address) view returns (address)",
    "function withdrawFoundationReward()",
    "function withdrawReward()",
];
