[
    "constructor(address _validator, address _manager, uint256 _percent, uint8 _type, uint8 _state)",
    "event AddMargin(address indexed sender, uint256 amount)",
    "event ChangeManager(address indexed manager)",
    "event ChangeState(uint8 indexed state)",
    "event ConfirmPercentChange(uint256 indexed percent)",
    "event Deposit(address indexed sender, uint256 amount)",
    "event Exit(address indexed validator)",
    "event ExitVote(address indexed sender, uint256 amount)",
    "event Punish(address indexed validator, uint256 amount)",
    "event RemoveIncoming(address indexed validator, uint256 amount)",
    "event SubmitPercentChange(uint256 indexed percent)",
    "event Withdraw(address indexed sender, uint256 amount)",
    "event WithdrawMargin(address indexed sender, uint256 amount)",
    "event WithdrawValidatorReward(address indexed sender, uint256 amount)",
    "event WithdrawVoteReward(address indexed sender, uint256 amount)",
    "function JailPeriod() view returns (uint256)",
    "function MarginLockPeriod() view returns (uint256)",
    "function MaxValidators() view returns (uint16)",
    "function PercentChangeLockPeriod() view returns (uint256)",
    "function PoaMinMargin() view returns (uint256)",
    "function PosMinMargin() view returns (uint256)",
    "function PunishAmount() view returns (uint256)",
    "function WithdrawLockPeriod() view returns (uint256)",
    "function addMargin() payable",
    "function changeManager(address _manager)",
    "function confirmPercentChange()",
    "function deposit() payable",
    "function exit()",
    "function exitBlk() view returns (uint256)",
    "function exitVote(uint256 _amount)",
    "function getPendingReward(address _voter) view returns (uint256)",
    "function getValidatorPendingReward() view returns (uint256)",
    "function initialize()",
    "function initialized() view returns (bool)",
    "function isIdleStateLike() view returns (bool)",
    "function manager() view returns (address)",
    "function margin() view returns (uint256)",
    "function pendingPercentChange() view returns (uint256 newPercent, uint256 submitBlk)",
    "function percent() view returns (uint256)",
    "function punish()",
    "function punishBlk() view returns (uint256)",
    "function punishContract() view returns (address)",
    "function receiveReward() payable",
    "function removeValidatorIncoming()",
    "function state() view returns (uint8)",
    "function submitPercentChange(uint256 _percent)",
    "function switchState(bool pause)",
    "function totalVote() view returns (uint256)",
    "function validator() view returns (address)",
    "function validatorType() view returns (uint8)",
    "function validatorsContract() view returns (address)",
    "function voters(address) view returns (uint256 amount, uint256 rewardDebt, uint256 withdrawPendingAmount, uint256 withdrawExitBlock)",
    "function withdrawMargin()",
    "function withdrawValidatorReward() payable",
];
